### ISSUE TITLE
Comments issue

### ISSUE THREAD

**Issue by jrvleet** [jrvleet/bcdb#1]
1. User Story "As a user I want to be able to comment on Badass Chick profiles."
2. https://i.imgur.com/DKfHitb.png
3.  I've tried variations on the code in my views/comments/_form.html.erb and in views/comments/index.html.erb
https://i.imgur.com/fLsku2f.png
https://i.imgur.com/OdgcCz6.png

**Comment by tambling** [comment]
You need to have `resources :comments` in your `routes.rb`. When you pass it `@comment`, it's seeing that it's a `Comment` and assuming that there will be something called `comments_path` that it can `POST` to. Check your `routes.rb` file and run `rake routes` and make sure there's a create route for `comments`.

**Comment by jrvleet** [comment]
This is what my routes.rb looks like:
https://i.imgur.com/Yo6uPjv.png
now I'm getting this error:
https://i.imgur.com/haRlpPV.png

**Comment by tambling** [comment]
`resources :comments, only: [:create]`
